[package]
name = "wakka"
version = "0.0.1"
authors = ["Michael Mason <TeaUponTweed@gmail.com>"]

[dependencies]
image = "*"
num = "*"
rand = "*"
specs = "*"
piston_window = "*"
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"
